export const mockData = [
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
  {
    id: "ebv",
    url: "https://cdn2.thecatapi.com/images/ebv.jpg",
    width: 176,
    height: 540,
    breeds: [],
    favourite: {},
  },
];
